- jobFamily: "a"
  url: "http://localhost:8080/"
  requestBody: ""
  description: ""
- jobFamily: "b"
  url: "http://localhost:8081/"
  requestBody: ""
  description: ""
- jobFamily: "c"
  url: "http://localhost:8082/"
  requestBody: ""
  description: ""
- jobFamily: "d"
  url: "http://localhost:8083/"
  requestBody: ""
  description: ""