apiVersion: v1
kind: Service
metadata:
  name: k8s-job-monitor-service
spec:
  type: ClusterIP
  selector:
    app: k8s-job-monitor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
